-- Auto-generated seed from airports.json
INSERT INTO supported_airports (iata_code, country_code, name, skytrax_review_slug, skytrax_rating_slug, google_maps_url) VALUES
  ('LHR', 'GB', 'London Heathrow', 'london-heathrow-airport', 'london-heathrow-airport', 'https://maps.app.goo.gl/o2vB1du9UYYTRAsd6'),
  ('LGW', 'GB', 'London Gatwick', 'london-gatwick-airport', 'london-gatwick-airport', 'https://maps.app.goo.gl/WdNU9vBeMXenzgTm9'),
  ('LTN', 'GB', 'London Luton', 'luton-airport', 'london-luton-airport', 'https://maps.app.goo.gl/eAAroWfsNfMZuqFp6'),
  ('OPO', 'PT', 'Porto', 'porto-airport', 'porto-airport', 'https://maps.app.goo.gl/ZYwTcczCpiEdvg4t6'),
  ('MAD', 'ES', 'Madrid Barajas', 'madrid-barajas-airport', 'madrid-barajas-airport', 'https://maps.app.goo.gl/wPSnnJAQkBomwsGz9'),
  ('BCN', 'ES', 'Barcelona El Prat', 'barcelona-airport', 'barcelona-el-prat-airport', 'https://maps.app.goo.gl/iBMM6NR2K9RoUM5E6'),
  ('BER', 'DE', 'Berlin Brandenburg', 'berlin-brandenburg-airport', 'berlin-brandenburg-airport', 'https://maps.app.goo.gl/RQF3nFTesreLbbYa6'),
  ('MUC', 'DE', 'Munich International Airport', 'munich-airport', 'munich-airport', 'https://maps.app.goo.gl/hzRw1okNJwXnTzCW6'),
  ('CDG', 'FR', 'Paris Charles de Gaulle', 'paris-cdg-airport', 'paris-cdg-airport', 'https://maps.app.goo.gl/jwJa6f7EUQLz2wxj8'),
  ('NCE', 'FR', 'Nice Côte d''Azur', 'nice-cote-dazur-airport', 'nice-airport', 'https://maps.app.goo.gl/SRNL8GvAKh29GPQv5'),
  ('AMS', 'NL', 'Amsterdam Schiphol', 'amsterdam-schiphol-airport', 'amsterdam-airport-schiphol', 'https://maps.app.goo.gl/SKMc7G5zAtzW5BZ7A'),
  ('CPH', 'DK', 'Copenhagen', 'copenhagen-airport', 'copenhagen-airport', 'https://maps.app.goo.gl/eFtdvWo4NAQh4bx28'),
  ('FCO', 'IT', 'Leonardo da Vinci International Airport', 'rome-fiumicino-airport', 'rome-fiumicino-airport', 'https://maps.app.goo.gl/wasVuojVgYiKbJb19'),
  ('WAW', 'PL', 'Warsaw Chopin', 'warsaw-chopin-airport', 'warsaw-chopin-airport', 'https://maps.app.goo.gl/9f5dBWiQt6nzWzDi6'),
  ('BUD', 'HU', 'Budapest', 'budapest-ferihegy-airport', 'budapest-airport', 'https://maps.app.goo.gl/USbiekSoPj1PqENT8'),
  ('CLJ', 'RO', 'Avram Iancu Cluj International Airport', 'cluj-napoca-airport', NULL, 'https://maps.app.goo.gl/C3XaMJrKEmojhgsv8'),
  ('LIS', 'PT', 'Humberto Delgado Airport', 'lisbon-airport-rating', 'lisbon-airport', 'https://maps.app.goo.gl/NXsmM2vmGbZkBGmz5'),
  ('FAO', 'PT', 'Faro International Airport', 'faro-airport-rating', 'faro-airport', 'https://maps.app.goo.gl/tQrMZZ1JYGjq71ca9'),
  ('AGP', 'ES', 'Malaga-Costa del Sol Airport', 'malaga-airport', 'malaga-costa-del-sol-airport', 'https://maps.app.goo.gl/suYy6zV1s9pB2KTFA'),
  ('ALC', 'ES', 'Alicante-Elche Airport', 'alicante-airport', NULL, 'https://maps.app.goo.gl/WLHuinE5bYwh93CC9'),
  ('PMI', 'ES', 'Palma de Mallorca Airport', 'palma-de-mallorca-airport-rating', 'palma-de-mallorca-airport', 'https://maps.app.goo.gl/AY1EQLKexPzJLXeN8'),
  ('IBZ', 'ES', 'Ibiza Airport', 'ibiza-airport', 'ibiza-airport', 'https://maps.app.goo.gl/FMus12YFMwQikPsMA'),
  ('BIO', 'ES', 'Bilbao Airport', 'bilbao-airport', 'bilbao-airport', 'https://maps.app.goo.gl/sG1QpE1RXmiyazxC7'),
  ('VLC', 'ES', 'Valencia Airport', 'valencia-airport', 'valencia-airport', 'https://maps.app.goo.gl/RnQEydTDRu4XNF64A'),
  ('SVQ', 'ES', 'Seville Airport', 'seville-airport', 'seville-airport', 'https://maps.app.goo.gl/Kh1XrpzDVj1JDKgf6'),
  ('LPA', 'ES', 'Gran Canaria Airport', 'gran-canaria-airport', 'gran-canaria-airport', 'https://maps.app.goo.gl/MkujbD8f1WN3gqSbA'),
  ('TFS', 'ES', 'Tenerife South Airport', 'tenerife-airport', NULL, 'https://maps.app.goo.gl/N5Kbgz2eFkgHPRmF8'),
  ('TFN', 'ES', 'Tenerife North Airport', NULL, NULL, 'https://maps.app.goo.gl/BJddyi1ZVS1TZsf87'),
  ('ACE', 'ES', 'Lanzarote Airport', 'lanzarote-arrecife-airport', NULL, 'https://maps.app.goo.gl/udmhsAYhh8PHiGDC9'),
  ('FUE', 'ES', 'Fuerteventura Airport', 'fuerteventura-airport', NULL, 'https://maps.app.goo.gl/CVj6CU42tvZAD7oU7'),
  ('MAH', 'ES', 'Menorca Airport', 'mahon-airport', NULL, 'https://maps.app.goo.gl/V3FRBmgjszPQFfc18'),
  ('SCQ', 'ES', 'Santiago de Compostela Airport', 'santiago-de-compostela', NULL, 'https://maps.app.goo.gl/wf4Kjsrnnqvqjx8S8'),
  ('OVD', 'ES', 'Asturias Airport', 'asturias-airport', NULL, 'https://maps.app.goo.gl/gUipFCHDpviSA7eT6'),
  ('LCG', 'ES', 'A Coruna Airport', NULL, NULL, 'https://maps.app.goo.gl/o13KF4hKFWKEA2ei6'),
  ('GRX', 'ES', 'Granada-Jaen Airport', 'granada-airport', NULL, 'https://maps.app.goo.gl/9Mhw3FBsgmeBFNGG8'),
  ('SDR', 'ES', 'Santander Airport', 'santander-airport', NULL, 'https://maps.app.goo.gl/BqqRwU697ixzNgo26'),
  ('EAS', 'ES', 'San Sebastian Airport', 'san-sebastian-airport', NULL, 'https://maps.app.goo.gl/j9mkst2ov1rSkyjJ6'),
  ('VGO', 'ES', 'Vigo Airport', NULL, NULL, 'https://maps.app.goo.gl/LW8whxWWacmvoAwA6'),
  ('RMU', 'ES', 'Murcia Airport', NULL, 'murcia-san-javier-airport', 'https://maps.app.goo.gl/tFd8bGQQvWLPYhjDA'),
  ('GRO', 'ES', 'Girona Airport', 'girona-airport', NULL, 'https://maps.app.goo.gl/x5JJ8F6UN9MkfhPo8'),
  ('PNA', 'ES', 'Pamplona Airport', NULL, NULL, 'https://maps.app.goo.gl/Eezn5yXbTGhho4f36')
ON CONFLICT (iata_code) DO NOTHING;
