/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperatorsIndexRouteImport } from './routes/operators/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OperatorsIdRouteImport } from './routes/operators/$id'
import { Route as CountriesCodeRouteImport } from './routes/countries_.$code'
import { Route as AirportIataRouteImport } from './routes/airport.$iata'
import { Route as AdminOperatorsRouteImport } from './routes/admin/operators'
import { Route as AdminDataGapsRouteImport } from './routes/admin/data-gaps'
import { Route as AdminAirportsRouteImport } from './routes/admin/airports'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs.index'
import { Route as AdminJobsIdRouteImport } from './routes/admin/jobs.$id'

const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsIndexRoute = OperatorsIndexRouteImport.update({
  id: '/operators/',
  path: '/operators/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsIdRoute = OperatorsIdRouteImport.update({
  id: '/operators/$id',
  path: '/operators/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCodeRoute = CountriesCodeRouteImport.update({
  id: '/countries_/$code',
  path: '/countries/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportIataRoute = AirportIataRouteImport.update({
  id: '/airport/$iata',
  path: '/airport/$iata',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperatorsRoute = AdminOperatorsRouteImport.update({
  id: '/admin/operators',
  path: '/admin/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataGapsRoute = AdminDataGapsRouteImport.update({
  id: '/admin/data-gaps',
  path: '/admin/data-gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAirportsRoute = AdminAirportsRouteImport.update({
  id: '/admin/airports',
  path: '/admin/airports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/admin/jobs/',
  path: '/admin/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIdRoute = AdminJobsIdRouteImport.update({
  id: '/admin/jobs/$id',
  path: '/admin/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countries': typeof CountriesRoute
  '/rankings': typeof RankingsRoute
  '/admin/airports': typeof AdminAirportsRoute
  '/admin/data-gaps': typeof AdminDataGapsRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/airport/$iata': typeof AirportIataRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/operators/$id': typeof OperatorsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/operators/': typeof OperatorsIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countries': typeof CountriesRoute
  '/rankings': typeof RankingsRoute
  '/admin/airports': typeof AdminAirportsRoute
  '/admin/data-gaps': typeof AdminDataGapsRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/airport/$iata': typeof AirportIataRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/operators/$id': typeof OperatorsIdRoute
  '/admin': typeof AdminIndexRoute
  '/operators': typeof OperatorsIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countries': typeof CountriesRoute
  '/rankings': typeof RankingsRoute
  '/admin/airports': typeof AdminAirportsRoute
  '/admin/data-gaps': typeof AdminDataGapsRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/airport/$iata': typeof AirportIataRoute
  '/countries_/$code': typeof CountriesCodeRoute
  '/operators/$id': typeof OperatorsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/operators/': typeof OperatorsIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/countries'
    | '/rankings'
    | '/admin/airports'
    | '/admin/data-gaps'
    | '/admin/operators'
    | '/airport/$iata'
    | '/countries/$code'
    | '/operators/$id'
    | '/admin/'
    | '/operators/'
    | '/admin/jobs/$id'
    | '/admin/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/countries'
    | '/rankings'
    | '/admin/airports'
    | '/admin/data-gaps'
    | '/admin/operators'
    | '/airport/$iata'
    | '/countries/$code'
    | '/operators/$id'
    | '/admin'
    | '/operators'
    | '/admin/jobs/$id'
    | '/admin/jobs'
  id:
    | '__root__'
    | '/'
    | '/countries'
    | '/rankings'
    | '/admin/airports'
    | '/admin/data-gaps'
    | '/admin/operators'
    | '/airport/$iata'
    | '/countries_/$code'
    | '/operators/$id'
    | '/admin/'
    | '/operators/'
    | '/admin/jobs/$id'
    | '/admin/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountriesRoute: typeof CountriesRoute
  RankingsRoute: typeof RankingsRoute
  AdminAirportsRoute: typeof AdminAirportsRoute
  AdminDataGapsRoute: typeof AdminDataGapsRoute
  AdminOperatorsRoute: typeof AdminOperatorsRoute
  AirportIataRoute: typeof AirportIataRoute
  CountriesCodeRoute: typeof CountriesCodeRoute
  OperatorsIdRoute: typeof OperatorsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OperatorsIndexRoute: typeof OperatorsIndexRoute
  AdminJobsIdRoute: typeof AdminJobsIdRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/': {
      id: '/operators/'
      path: '/operators'
      fullPath: '/operators/'
      preLoaderRoute: typeof OperatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/$id': {
      id: '/operators/$id'
      path: '/operators/$id'
      fullPath: '/operators/$id'
      preLoaderRoute: typeof OperatorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries_/$code': {
      id: '/countries_/$code'
      path: '/countries/$code'
      fullPath: '/countries/$code'
      preLoaderRoute: typeof CountriesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport/$iata': {
      id: '/airport/$iata'
      path: '/airport/$iata'
      fullPath: '/airport/$iata'
      preLoaderRoute: typeof AirportIataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operators': {
      id: '/admin/operators'
      path: '/admin/operators'
      fullPath: '/admin/operators'
      preLoaderRoute: typeof AdminOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-gaps': {
      id: '/admin/data-gaps'
      path: '/admin/data-gaps'
      fullPath: '/admin/data-gaps'
      preLoaderRoute: typeof AdminDataGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/airports': {
      id: '/admin/airports'
      path: '/admin/airports'
      fullPath: '/admin/airports'
      preLoaderRoute: typeof AdminAirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/$id': {
      id: '/admin/jobs/$id'
      path: '/admin/jobs/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AdminJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountriesRoute: CountriesRoute,
  RankingsRoute: RankingsRoute,
  AdminAirportsRoute: AdminAirportsRoute,
  AdminDataGapsRoute: AdminDataGapsRoute,
  AdminOperatorsRoute: AdminOperatorsRoute,
  AirportIataRoute: AirportIataRoute,
  CountriesCodeRoute: CountriesCodeRoute,
  OperatorsIdRoute: OperatorsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  OperatorsIndexRoute: OperatorsIndexRoute,
  AdminJobsIdRoute: AdminJobsIdRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
