/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AirportIataRouteImport } from './routes/airport.$iata'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminAirportsRouteImport } from './routes/admin/airports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportIataRoute = AirportIataRouteImport.update({
  id: '/airport/$iata',
  path: '/airport/$iata',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAirportsRoute = AdminAirportsRouteImport.update({
  id: '/admin/airports',
  path: '/admin/airports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/airports': typeof AdminAirportsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/airport/$iata': typeof AirportIataRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/airports': typeof AdminAirportsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/airport/$iata': typeof AirportIataRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/airports': typeof AdminAirportsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/airport/$iata': typeof AirportIataRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/airports'
    | '/admin/jobs'
    | '/airport/$iata'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/airports' | '/admin/jobs' | '/airport/$iata' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/airports'
    | '/admin/jobs'
    | '/airport/$iata'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAirportsRoute: typeof AdminAirportsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AirportIataRoute: typeof AirportIataRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport/$iata': {
      id: '/airport/$iata'
      path: '/airport/$iata'
      fullPath: '/airport/$iata'
      preLoaderRoute: typeof AirportIataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/airports': {
      id: '/admin/airports'
      path: '/admin/airports'
      fullPath: '/admin/airports'
      preLoaderRoute: typeof AdminAirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAirportsRoute: AdminAirportsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AirportIataRoute: AirportIataRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
