/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/data-gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find airports with missing or stale data sources. */
        get: operations["data_gaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all jobs. */
        get: operations["list_jobs"];
        put?: never;
        /** Start a pipeline job. */
        post: operations["start_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single job by ID. */
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a running job. */
        post: operations["cancel_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Incremental refresh all enabled airports (all sources, no full refresh). */
        post: operations["refresh_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger scoring only (no data fetching). */
        post: operations["trigger_scoring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/supported-airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all supported airports with their source statuses. */
        get: operations["list_supported_airports"];
        put?: never;
        /** Create a new supported airport. */
        post: operations["create_supported_airport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/supported-airports/{iata}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a supported airport. */
        delete: operations["delete_supported_airport"];
        options?: never;
        head?: never;
        /** Update a supported airport (partial update). */
        patch: operations["update_supported_airport"];
        trace?: never;
    };
    "/api/airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all airports with their latest scores. */
        get: operations["list_airports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/airports/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get airport rankings (semantic alias for list). */
        get: operations["get_rankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/airports/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search airports by IATA code, name, or city. */
        get: operations["search_airports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/airports/{iata}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full airport detail by IATA code. */
        get: operations["get_airport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List aggregated country-level stats for all tracked airports. */
        get: operations["list_countries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/{code}/airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List airports in a specific country. */
        get: operations["airports_by_country"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/full-refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cron: full refresh of all airports, all sources, then score. */
        post: operations["cron_full_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cron: run reviews (Skytrax + Google) only. */
        post: operations["cron_reviews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/sentiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cron: run sentiment pipeline + scoring only. */
        post: operations["cron_sentiment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AirportDetailResponse: {
            airportType: string;
            /** Format: double */
            annualCapacityM?: number | null;
            /** Format: double */
            annualPaxLatestM?: number | null;
            carbonAccreditation: components["schemas"]["CarbonAccreditationResponse"][];
            city: string;
            country?: null | components["schemas"]["CountryResponse"];
            countryCode: string;
            /** Format: int32 */
            elevationFt?: number | null;
            googleAgg?: null | components["schemas"]["GoogleAggResponse"];
            groundTransport: components["schemas"]["GroundTransportResponse"][];
            hubStatus: components["schemas"]["HubStatusResponse"][];
            iataCode?: string | null;
            icaoCode?: string | null;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            lastMajorReno?: number | null;
            /** Format: int32 */
            latestPaxYear?: number | null;
            lounges: components["schemas"]["LoungeResponse"][];
            name: string;
            /** Format: int32 */
            openedYear?: number | null;
            operationalStats: components["schemas"]["OperationalStatResponse"][];
            operator?: null | components["schemas"]["OrganisationResponse"];
            owner?: null | components["schemas"]["OrganisationResponse"];
            paxYearly: components["schemas"]["PaxYearlyResponse"][];
            ranking: components["schemas"]["RankingResponse"];
            recentReviews: components["schemas"]["RecentReviewResponse"][];
            routesOut: components["schemas"]["RouteResponse"][];
            runways: components["schemas"]["RunwayResponse"][];
            scores: components["schemas"]["ScoreResponse"][];
            sentimentSnapshots: components["schemas"]["SentimentSnapshotResponse"][];
            shortName?: string | null;
            skytraxUrl?: string | null;
            sourceBreakdown: components["schemas"]["SourceBreakdownResponse"][];
            /** Format: int32 */
            terminalCount?: number | null;
            timezone?: string | null;
            /** Format: int32 */
            totalGates?: number | null;
            websiteUrl?: string | null;
            wikipediaSnapshots: components["schemas"]["WikipediaSnapshotResponse"][];
            wikipediaUrl?: string | null;
        };
        AirportListItem: {
            city: string;
            countryCode: string;
            iataCode: string;
            name: string;
            /** Format: double */
            scoreSentimentVelocity?: number | null;
            /** Format: double */
            scoreTotal?: number | null;
        };
        CarbonAccreditationResponse: {
            /** Format: int32 */
            level?: number | null;
            levelName?: string | null;
            /** Format: int32 */
            reportYear?: number | null;
        };
        CountryResponse: {
            code: string;
            name: string;
        };
        /** @description Aggregated country-level stats for all tracked airports. */
        CountrySummary: {
            /** Format: int64 */
            airportCount: number;
            /** Format: double */
            avgOnTime?: number | null;
            /** Format: double */
            avgScore?: number | null;
            /** Format: double */
            avgSentimentPositive?: number | null;
            /** Format: double */
            bestScore?: number | null;
            code: string;
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
            name: string;
            /** Format: int64 */
            totalPax?: number | null;
            /** Format: int64 */
            totalRoutes?: number | null;
            /** Format: double */
            worstScore?: number | null;
        };
        /** @description For creating a supported airport via the admin API. */
        CreateSupportedAirport: {
            country_code: string;
            google_maps_url?: string | null;
            iata_code: string;
            name: string;
            skytrax_rating_slug?: string | null;
            skytrax_review_slug?: string | null;
        };
        DataGapResponse: {
            iataCode: string;
            lastFetchedAt?: string | null;
            lastStatus: string;
            name: string;
            source: string;
        };
        GoogleAggResponse: {
            /** Format: int64 */
            count: number;
            /** Format: double */
            rating?: number | null;
        };
        GroundTransportResponse: {
            hasBus?: boolean | null;
            hasDirectRail?: boolean | null;
            hasMetro?: boolean | null;
            hasRail?: boolean | null;
            hasTram?: boolean | null;
            /** Format: int32 */
            transportModesCount?: number | null;
        };
        HubStatusResponse: {
            airlineName?: string | null;
            statusType?: string | null;
        };
        JobInfo: {
            airports: string[];
            completedAt?: string | null;
            error?: string | null;
            fullRefresh: boolean;
            id: string;
            progress: components["schemas"]["JobProgress"];
            score: boolean;
            sources: string[];
            startedAt?: string | null;
            status: string;
        };
        JobProgress: {
            airportsCompleted: number;
            airportsTotal: number;
            currentAirport?: string | null;
            currentSource?: string | null;
        };
        LoungeResponse: {
            loungeName?: string | null;
            source?: string | null;
            terminal?: string | null;
        };
        OperationalStatResponse: {
            /** Format: double */
            avgDelayMinutes?: number | null;
            /** Format: double */
            cancellationPct?: number | null;
            /** Format: int32 */
            cancelledFlights?: number | null;
            /** Format: double */
            delayAirportPct?: number | null;
            /** Format: double */
            delayAtcPct?: number | null;
            /** Format: double */
            delayCarrierPct?: number | null;
            /** Format: double */
            delayPct?: number | null;
            /** Format: double */
            delaySecurityPct?: number | null;
            /** Format: double */
            delayWeatherPct?: number | null;
            /** Format: int32 */
            delayedFlights?: number | null;
            /** Format: int32 */
            periodMonth?: number | null;
            /** Format: int32 */
            periodYear: number;
            source?: string | null;
            /** Format: int32 */
            totalFlights?: number | null;
        };
        OrganisationResponse: {
            countryCode?: string | null;
            /** Format: int32 */
            id: number;
            name: string;
            orgType?: string | null;
            ownershipModel?: string | null;
            shortName?: string | null;
        };
        PaxYearlyResponse: {
            /** Format: int32 */
            aircraftMovements?: number | null;
            /** Format: int64 */
            domesticPax?: number | null;
            /** Format: int64 */
            internationalPax?: number | null;
            source?: string | null;
            /** Format: int64 */
            totalPax?: number | null;
            /** Format: int32 */
            year: number;
        };
        RankingResponse: {
            /** Format: int64 */
            position?: number | null;
            /** Format: int64 */
            total: number;
        };
        RecentReviewResponse: {
            /** Format: int32 */
            overallRating?: number | null;
            /** Format: date */
            reviewDate?: string | null;
            reviewText?: string | null;
            source?: string | null;
        };
        RouteDestinationResponse: {
            city?: string | null;
            countryCode?: string | null;
            name?: string | null;
        };
        RouteResponse: {
            airlineIata?: string | null;
            airlineName?: string | null;
            destination?: null | components["schemas"]["RouteDestinationResponse"];
            destinationIata?: string | null;
            destinationIcao?: string | null;
            /** Format: int32 */
            flightsPerMonth?: number | null;
        };
        RunwayResponse: {
            closed?: boolean | null;
            /** Format: int32 */
            id: number;
            ident?: string | null;
            /** Format: int32 */
            lengthFt?: number | null;
            lighted?: boolean | null;
            surface?: string | null;
            /** Format: int32 */
            widthFt?: number | null;
        };
        ScoreResponse: {
            commentary?: string | null;
            isLatest?: boolean | null;
            /** Format: double */
            scoreConnectivity?: number | null;
            /** Format: double */
            scoreInfrastructure?: number | null;
            /** Format: double */
            scoreOperational?: number | null;
            /** Format: double */
            scoreOperator?: number | null;
            /** Format: double */
            scoreSentiment?: number | null;
            /** Format: double */
            scoreSentimentVelocity?: number | null;
            /** Format: double */
            scoreTotal?: number | null;
            scoreVersion?: string | null;
            scoredAt?: string | null;
        };
        SearchResult: {
            city: string;
            countryCode: string;
            iataCode: string;
            name: string;
            /** Format: double */
            scoreTotal?: number | null;
        };
        SentimentSnapshotResponse: {
            /** Format: double */
            avgRating?: number | null;
            /** Format: double */
            negativePct?: number | null;
            /** Format: double */
            neutralPct?: number | null;
            notes?: string | null;
            /** Format: double */
            positivePct?: number | null;
            /** Format: int32 */
            reviewCount?: number | null;
            /** Format: double */
            scoreCleanliness?: number | null;
            /** Format: double */
            scoreFoodBev?: number | null;
            /** Format: double */
            scoreQueuing?: number | null;
            /** Format: double */
            scoreShopping?: number | null;
            /** Format: double */
            scoreStaff?: number | null;
            /** Format: double */
            scoreTransport?: number | null;
            /** Format: double */
            scoreWayfinding?: number | null;
            /** Format: double */
            scoreWifi?: number | null;
            /** Format: int32 */
            skytraxStars?: number | null;
            /** Format: int32 */
            snapshotQuarter?: number | null;
            /** Format: int32 */
            snapshotYear?: number | null;
            source?: string | null;
        };
        SourceBreakdownResponse: {
            /** Format: int64 */
            count: number;
            source: string;
        };
        SourceStatusResponse: {
            lastError?: string | null;
            lastFetchedAt?: string | null;
            /** Format: int32 */
            lastRecordCount?: number | null;
            lastStatus: string;
            source: string;
        };
        StartJobRequest: {
            airports?: string[] | null;
            fullRefresh?: boolean | null;
            score?: boolean | null;
            sources?: string[] | null;
        };
        SupportedAirportWithStatus: {
            countryCode: string;
            createdAt: string;
            enabled: boolean;
            googleMapsUrl?: string | null;
            hasScore: boolean;
            iataCode: string;
            name: string;
            skytraxRatingSlug?: string | null;
            skytraxReviewSlug?: string | null;
            sources: components["schemas"]["SourceStatusResponse"][];
            updatedAt: string;
        };
        /** @description For updating a supported airport via the admin API. */
        UpdateSupportedAirport: {
            country_code?: string | null;
            enabled?: boolean | null;
            google_maps_url?: string | null;
            name?: string | null;
            skytrax_rating_slug?: string | null;
            skytrax_review_slug?: string | null;
        };
        WikipediaSnapshotResponse: {
            aciAwards?: unknown;
            fetchedAt?: string | null;
            milestoneNotes?: string | null;
            /** Format: int32 */
            openedYear?: number | null;
            operatorRaw?: string | null;
            ownerRaw?: string | null;
            ownershipNotes?: string | null;
            renovationNotes?: string | null;
            skytraxHistory?: unknown;
            /** Format: int32 */
            terminalCount?: number | null;
            terminalNames?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    data_gaps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airports with missing or stale data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataGapResponse"][];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"][];
                };
            };
        };
    };
    start_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartJobRequest"];
            };
        };
        responses: {
            /** @description Job started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Failed to start job */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh job started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Failed to start refresh */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_scoring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scoring completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scoring failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_supported_airports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All supported airports with source status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportedAirportWithStatus"][];
                };
            };
        };
    };
    create_supported_airport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupportedAirport"];
            };
        };
        responses: {
            /** @description Airport created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportedAirportWithStatus"];
                };
            };
            /** @description Airport already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_supported_airport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description IATA airport code */
                iata: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airport deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Airport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_supported_airport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description IATA airport code */
                iata: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSupportedAirport"];
            };
        };
        responses: {
            /** @description Airport updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportedAirportWithStatus"];
                };
            };
            /** @description Airport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_airports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All scored airports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportListItem"][];
                };
            };
        };
    };
    get_rankings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airport rankings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportListItem"][];
                };
            };
        };
    };
    search_airports: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
        };
    };
    get_airport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description IATA airport code */
                iata: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airport detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportDetailResponse"];
                };
            };
            /** @description Airport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountrySummary"][];
                };
            };
        };
    };
    airports_by_country: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ISO country code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airports in country */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportListItem"][];
                };
            };
        };
    };
    cron_full_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
        };
    };
    cron_reviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
        };
    };
    cron_sentiment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
        };
    };
}
